#!/usr/bin/env bash
# =============================================================================
# Omarchy Custom - Touchpad (per-device config, pad only)
# =============================================================================
# Configures ONLY the laptop's touchpad:
#   • Pointer acceleration: "adaptive" profile (whereas Omarchy's global
#     setting is "flat", which disables all acceleration).
#   • Slightly increased pointer sensitivity.
#   • Slightly increased touch scroll sensitivity.
# The EXTERNAL MOUSE is NOT modified: the block is passed as per-device
# configuration (hl.device <name>) and only affects the detected touchpad.
#
# What this script does:
#   1. Detects the touchpad (hyprctl devices, read-only).
#   2. Regenerates ~/.config/hypr/touchpad.lua (hl.device block delimited by
#      markers, idempotent).
#   3. Registers require("hypr.touchpad") in hyprland.lua (delimited block,
#      idempotent, added after require("hypr.autostart")).
#   4. Reloads Hyprland and checks the config errors.
#
# Default values (environment variables to change them):
#   TOUCHPAD_NAME            device name (detected otherwise: *-touchpad)
#   TOUCHPAD_ACCEL           accel_profile by default  "adaptive"
#   TOUCHPAD_SENSITIVITY     sensitivity (pointer)     -0.2
#   TOUCHPAD_SCROLL_FACTOR   scroll_factor (scroll)     0.6
#
# Hyprland NOTE: SCROLL acceleration (scroll_points curve) is only exposed
# with accel_profile = "custom" and remains ambiguous for a touchpad; this
# module therefore increases scroll sensitivity via scroll_factor (0.4 → 0.6).
#
# Usage:
#   ./fix-touchpad.sh            # applies (idempotent), reload + check
#   ./fix-touchpad.sh --status   # status (detected device, current values)
#   ./fix-touchpad.sh --remove   # removes touchpad.lua + require, restores
#   ./fix-touchpad.sh -y         # non-interactive (equivalent to asking nothing)
#
# NOTE: if an Omarchy update overwrites hyprland.lua, rerunning this script
# is enough to restore the module registration.
# =============================================================================
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../lib/gui-run.bash"  # gui-run: reopen in a terminal when launched from a file manager
set -euo pipefail

info() { echo -e "\033[1;34m==>\033[0m $*"; }
ok()   { echo -e "\033[1;32m ✓\033[0m $*"; }
warn() { echo -e "\033[1;33m !\033[0m $*"; }
err()  { echo -e "\033[1;31m ✗\033[0m $*" >&2; }

REAL_HOME="${HOME}"
HYPR_DIR="$REAL_HOME/.config/hypr"
HYPRLAND="$HYPR_DIR/hyprland.lua"
TOUCHPAD_LUA="$HYPR_DIR/touchpad.lua"
BLOCK_START="-- >>> Omarchy_Custom_Scripts_Touchpad"
BLOCK_END="-- <<< Omarchy_Custom_Scripts_Touchpad"

ACCEL="${TOUCHPAD_ACCEL:-adaptive}"
SENS="${TOUCHPAD_SENSITIVITY:--0.2}"
SCROLL="${TOUCHPAD_SCROLL_FACTOR:-0.6}"

if [[ ! -d /usr/share/omarchy ]]; then
  echo "This script is meant for Omarchy." >&2
  exit 1
fi

STATUS_ONLY=false REMOVE=false
for a in "$@"; do case "$a" in
  -y|--yes) : ;;
  --status) STATUS_ONLY=true ;;
  --remove) REMOVE=true ;;
  -h|--help) sed -n '1,44p' "$0"; exit 0 ;;
  *) echo "Unknown option: $a (supported: -y --status --remove)" >&2; exit 1 ;;
esac; done

# -----------------------------------------------------------------------------
# Touchpad detection (read-only)
# -----------------------------------------------------------------------------
# Returns the device name (name of the pad, or empty). Does NOT touch the
# trackpoint nor the external mouse: only names ending in "-touchpad" are kept.
detect_touchpad(){
  if [[ -n ${TOUCHPAD_NAME:-} ]]; then echo "$TOUCHPAD_NAME"; return 0; fi
  if command -v hyprctl >/dev/null 2>&1; then
    hyprctl devices 2>/dev/null | awk '$1 ~ /-touchpad$/ { print $1; exit }'
  elif command -v libinput >/dev/null 2>&1; then
    libinput list-devices 2>/dev/null | grep -oE '[^ ]+-(touchpad|Touchpad)$' | head -1
  fi
}

# -----------------------------------------------------------------------------
# require block registered in hyprland.lua
# -----------------------------------------------------------------------------
require_block() {
  cat <<BLOCK_EOF
$BLOCK_START
require("hypr.touchpad")
$BLOCK_END
BLOCK_EOF
}

# -----------------------------------------------------------------------------
# 1. Generation of touchpad.lua (idempotent)
# -----------------------------------------------------------------------------
gen_touchpad_lua() {
  local name="$1"
  mkdir -p "$HYPR_DIR"
  local tmp
  tmp=$(mktemp)
  {
    echo "$BLOCK_START"
    echo "-- Configuration of the TOUCHPAD only (device \"$name\"). The external"
    echo "-- mouse keeps the global input.lua settings. Generated by"
    echo "-- touchpad/fix-touchpad.sh — rerun the script to re-apply."
    echo "hl.device({"
    echo "    name = \"$name\","
    echo "    -- Pointer acceleration: adaptive (the global \"flat\" profile disables it)"
    echo "    accel_profile = \"$ACCEL\","
    echo "    -- Pointer sensitivity: $SENS (global: -0.4)"
    echo "    sensitivity = $SENS,"
    echo "    -- Touch scroll sensitivity: $SCROLL (global touchpad: 0.4)"
    echo "    scroll_factor = $SCROLL,"
    echo "})"
    echo "$BLOCK_END"
  } > "$tmp"
  mv "$tmp" "$TOUCHPAD_LUA"
  ok "touchpad.lua written ($name)"
}

# -----------------------------------------------------------------------------
# 2. require("hypr.touchpad") registration in hyprland.lua
# -----------------------------------------------------------------------------
ensure_require() {
  [[ -f $HYPRLAND ]] || { err "$HYPRLAND not found — cannot register the module."; return 1; }
  local tmp_block tmp_out start_line end_line
  tmp_block=$(mktemp)
  tmp_out=$(mktemp)
  require_block > "$tmp_block"

  if grep -qF -- "$BLOCK_START" "$HYPRLAND"; then
    start_line=$(grep -nF -- "$BLOCK_START" "$HYPRLAND" | cut -d: -f1 | head -1)
    end_line=$(grep -nF -- "$BLOCK_END" "$HYPRLAND" | cut -d: -f1 | head -1)
    if [[ -z $start_line || -z $end_line || $end_line -le $start_line ]]; then
      rm -f "$tmp_block"; rm -f "$tmp_out"
      err "Inconsistent markers in $HYPRLAND, manual correction needed."
      return 1
    fi
    { head -n $((start_line - 1)) "$HYPRLAND"; cat "$tmp_block"; tail -n +$((end_line + 1)) "$HYPRLAND"; } > "$tmp_out"
    mv "$tmp_out" "$HYPRLAND"
    ok "require hypr.touchpad updated in $HYPRLAND"
  else
    # Backup of the user file on first insertion.
    if [[ ! -f "$HYPRLAND.bak" ]]; then
      cp "$HYPRLAND" "$HYPRLAND.bak"
      info "Initial backup: $HYPRLAND.bak"
    fi
    awk -v bk="$tmp_block" -v tok='require("hypr.autostart")' '
      index($0, tok) == 1 && !done {
        print; print ""
        while ((getline l < bk) > 0) print l
        close(bk); done = 1; next
      }
      { print }
      END {
        if (!done) { print ""; while ((getline l < bk) > 0) print l; close(bk) }
      }
    ' "$HYPRLAND" > "$tmp_out"
    mv "$tmp_out" "$HYPRLAND"
    ok "require hypr.touchpad added in $HYPRLAND"
  fi
  rm -f "$tmp_block"
}

remove_require() {
  [[ -f $HYPRLAND ]] || return 0
  if grep -qF -- "$BLOCK_START" "$HYPRLAND"; then
    local start_line end_line tmp
    start_line=$(grep -nF -- "$BLOCK_START" "$HYPRLAND" | cut -d: -f1 | head -1)
    end_line=$(grep -nF -- "$BLOCK_END" "$HYPRLAND" | cut -d: -f1 | head -1)
    if [[ -n $start_line && -n $end_line && $end_line -gt $start_line ]]; then
      tmp=$(mktemp)
      head -n $((start_line - 1)) "$HYPRLAND" > "$tmp"
      tail -n +$((end_line + 1)) "$HYPRLAND" >> "$tmp"
      mv "$tmp" "$HYPRLAND"
      ok "require block removed from $HYPRLAND"
    else
      warn "Inconsistent markers in $HYPRLAND, nothing removed."
    fi
  else
    ok "No touchpad require block in $HYPRLAND."
  fi
}

# -----------------------------------------------------------------------------
# 3. Hyprland reload + validation
# -----------------------------------------------------------------------------
reload_hypr() {
  if command -v hyprctl >/dev/null 2>&1; then
    if hyprctl reload >/dev/null 2>&1; then
      errors="$(hyprctl configerrors 2>/dev/null || true)"
      if [[ -n "$errors" ]]; then
        warn "Hyprland reloaded but with config warnings:"
        printf '%s\n' "$errors" | sed 's/^/    /'
      else
        ok "Hyprland reloaded, config valid"
      fi
    else
      warn "hyprctl reload failed — check manually: hyprctl reload"
    fi
  else
    warn "hyprctl not found (non-Hyprland session?) — config taken at next login."
  fi
}

# -----------------------------------------------------------------------------
# --status
# -----------------------------------------------------------------------------
do_status() {
  info "Touchpad configuration status"
  local name
  name="$(detect_touchpad)"
  if [[ -n $name ]]; then
    echo "  • Touchpad detected: $name"
  else
    if [[ -n ${TOUCHPAD_NAME:-} ]]; then
      echo "  • TOUCHPAD_NAME (forced): $TOUCHPAD_NAME"
      name="$TOUCHPAD_NAME"
    else
      echo "  • No touchpad detected (Hyprland session?)."
    fi
  fi
  if [[ -f $TOUCHPAD_LUA ]]; then
    echo "  • $TOUCHPAD_LUA: present"
    grep -E 'accel_profile|sensitivity|scroll_factor' "$TOUCHPAD_LUA" | sed 's/^/      /'
  else
    echo "  • $TOUCHPAD_LUA: absent"
  fi
  if [[ -f $HYPRLAND ]] && grep -qF -- "$BLOCK_START" "$HYPRLAND"; then
    echo "  • Registration in hyprland.lua: yes"
  else
    echo "  • Registration in hyprland.lua: no"
  fi
}

# -----------------------------------------------------------------------------
# --remove
# -----------------------------------------------------------------------------
do_remove() {
  [[ -f $TOUCHPAD_LUA ]] && { rm -f "$TOUCHPAD_LUA"; ok "touchpad.lua removed"; } \
                        || ok "touchpad.lua already absent."
  remove_require
  reload_hypr
}

# -----------------------------------------------------------------------------
# MAIN
# -----------------------------------------------------------------------------
if [[ $STATUS_ONLY == true ]]; then
  do_status
  exit 0
fi

if [[ $REMOVE == true ]]; then
  do_remove
  exit 0
fi

NAME="$(detect_touchpad)"
if [[ -z $NAME ]]; then
  err "No touchpad detected (run in the Hyprland session, or set TOUCHPAD_NAME=<name>)."
  exit 1
fi

info "Configuring the touchpad ($NAME)"
gen_touchpad_lua "$NAME"
ensure_require
reload_hypr

echo ""
info "Setup complete. Summary:"
echo "  • Device        -> $NAME (touchpad only, external mouse untouched)"
echo "  • Pointer       -> accel_profile $ACCEL, sensitivity $SENS (global -0.4)"
echo "  • Scroll        -> scroll_factor $SCROLL (global 0.4) — no scroll acceleration on the Hyprland side"
echo "  • Files         -> $TOUCHPAD_LUA + require in $HYPRLAND"
echo "  • Remove        -> $0 --remove"
