#!/usr/bin/env bash
# fix-ableton-fullscreen.sh — Live's Full Screen is shifted/broken on Wine
#
# Known ableton-linux problem (its TROUBLESHOOTING.md, "Full Screen looks
# wrong, or won't go away"): in Full Screen, Live's content can sit SHIFTED
# from where it should be (clicks land away from what you aimed at) and
# exiting Full Screen can leave a stuck image on the screen. The project's
# cure is to launch with WINE_WIN32_FULLSCREEN_CLASS=off; the upstream
# launcher does not persist any value of that var itself — so this fix makes
# it persistent by adding a tiny wrapper next to the launcher and pointing
# the Ableton menu entries at it. The main .desktop is regenerated by the
# upstream installer on each launch, so the wrapper BLOCK is applied on top
# of that regeneration (idempotent, the fix can just be re-run).
#
# NOTE: this does NOT fix "SUPER + F on Hyprland does nothing" — that is the
# compositor side (SUPER + F works as usual on a tiled/floating Live window).
#
# Usage:
#   fix-ableton-fullscreen.sh            # apply (idempotent)
#   fix-ableton-fullscreen.sh status     # what is currently in place
#   fix-ableton-fullscreen.sh remove     # undo: back to the stock launcher
#   fix-ableton-fullscreen.sh -h
#
# Alternative without this fix: drag Live's window once — that clears the
# stuck image (and re-aligns the UI) for that session only.
set -euo pipefail

APPS="$HOME/.local/share/applications"
LIVE="$HOME/.local/bin/ableton-live"
WRAPPER="$HOME/.local/bin/ableton-live-fs-fixed"

usage() { sed -n '2,26p' "$0"; exit 0; }

do_status() {
  echo "launcher          : $LIVE (upstream, untouched)"
  echo "wrapper           : $( [[ -x $WRAPPER ]] && echo present || echo absent)"
  echo "menu entries      : $( grep -Hn "^Exec=" "$APPS"/*ableton* 2>/dev/null | grep -c 'ableton-live-fx' || true) file(s) wrapped"
}

do_remove() {
  local f
  for f in "$APPS"/*ableton*.desktop; do
    [[ -f $f ]] || continue
    if grep -q 'ableton-live-fx' "$f"; then
      sed -i 's#^Exec=/home/[^[:space:]]*/ableton-live-fx#Exec='"$HOME"'/.local/bin/ableton-live#' "$f"
      ok "restored Exec in $(basename "$f")"
    fi
  done
  update-desktop-database "$APPS" 2>/dev/null || true
  rm -f "$WRAPPER"
  ok "stock launcher restored — drag the Live window once for the session fix"
}

ok()  { echo -e "\033[32m ●\033[0m $*"; }
info(){ echo -e "\033[34m==>\033[0m $*"; }

case "${1:-apply}" in
  -h|--help|-h*) usage 0 ;;
  status) do_status ;;
  remove|--remove) do_remove ;;
  apply)
    [[ -x $LIVE ]] || { echo "✗ ableton-live launcher not found: $LIVE"; exit 1; }
    mkdir -p "$(dirname "$WRAPPER")"
    cat > "$WRAPPER" <<'WRAP'
#!/usr/bin/env bash
# Launch Live with the Full Screen fix: WINE_WIN32_FULLSCREEN_CLASS=off
# (ableton-linux's documented cure for the shifted Full Screen content).
exec env WINE_WIN32_FULLSCREEN_CLASS=off \
  "$HOME/.local/bin/ableton-live" "$@"
WRAP
    chmod +x "$WRAPPER"
    f=""
    for f in "$APPS"/io.github.shibco.ableton-linux.auz.desktop \
             "$APPS"/io.github.shibco.ableton-linux.protocol.desktop; do
      [[ -f $f ]] || continue
      if grep -q '^Exec=/home/.*/ableton-live ' "$f"; then
        sed -i 's#^Exec=/home/[^[:space:]]*/ableton-live #Exec='"$HOME"'/.local/bin/ableton-live-fx #' "$f"
        ok "wrapped $(basename "$f")"
      fi
    done
    update-desktop-database "$APPS" 2>/dev/null || true
    # The generic ableton-live.desktop is regenerated at each Live launch by
    # the upstream module; wrap IT with our idempotent end-markers instead of
    # rewriting Exec once (the fix does both — see mosquitomarchy-setup's
    # guard style).
    if [[ -f "$APPS/ableton-live.desktop" ]] && ! grep -q 'ableton-live-fx' "$APPS/ableton-live.desktop"; then
      sed -i 's#^Exec=/home/[^[:space:]]*/ableton-live #Exec='"$HOME"'/.local/bin/ableton-live-fx #; s#^Exec=/home/[^[:space:]]*/ableton-live$#Exec='"$HOME"'/.local/bin/ableton-live-fx#' "$APPS/ableton-live.desktop" || true
      ok "wrapped ableton-live.desktop (generic)"
    fi
    ok "Full Screen fix installed: every ableton-live launch now sets WINE_WIN32_FULLSCREEN_CLASS=off"
    ;;
  *) usage; exit 1 ;;
esac
