#!/usr/bin/env bash
# lib/elevate.bash — shared privilege-elevation helper (mq_sudo).
#
# Goal: when a mosquitOmarchy script needs root but is NOT already running as
# root, prefer the native Omarchy polkit agent prompt (pkexec) over a terminal
# sudo password prompt. `mq_sudo CMD [ARGS...]` behaves exactly like
# `sudo CMD [ARGS...]`; it only changes *how* the password is asked for:
#   1. EUID == 0                      -> run "$@" directly.
#   2. `sudo -n -v` succeeds        -> sudo "$@"   (passwordless / cached).
#   3. pkexec + a usable polkit agent -> pkexec "$@" (native GUI prompt).
#   4. otherwise                      -> sudo "$@"   (terminal prompt).
#
# pkexec prompts once per invocation (polkit does not cache credentials the
# way sudo does), so callers that need several root steps should batch them
# into a single elevated `mq_sudo bash -c '...'` where practical.
#
# This file is functions-only and safe to source repeatedly.
[[ -n ${MQ_ELEVATE_SOURCED:-} ]] && return 0
MQ_ELEVATE_SOURCED=1

# True only when pkexec could actually reach an authentication agent: a
# session bus and a graphical session must both be present, otherwise pkexec
# fails with "No authentication agent found" instead of showing a prompt.
mq_polkit_agent_usable() {
  command -v pkexec >/dev/null 2>&1 || return 1
  [[ -n ${DBUS_SESSION_BUS_ADDRESS:-} ]] || return 1
  [[ -n ${WAYLAND_DISPLAY:-} || -n ${DISPLAY:-} ]] || return 1
  return 0
}

# pkexec aborts when $SHELL is set to a value that is not listed in
# /etc/shells ("The value for the SHELL variable was not found in the
# /etc/shells file"), which some TUI / managed/graphical environments export.
# Return a shell path pkexec accepts: the current one when valid, otherwise a
# listed one.
mq_sane_shell() {
  local s="${SHELL:-}" line
  if [[ -n $s && -x $s ]]; then
    while IFS= read -r line; do
      [[ $line == "$s" ]] && { printf '%s' "$s"; return 0; }
    done < /etc/shells 2>/dev/null
  fi
  for line in /bin/bash /usr/bin/bash /bin/sh /usr/bin/sh; do
    [[ -x $line ]] && grep -qxF "$line" /etc/shells 2>/dev/null && { printf '%s' "$line"; return 0; }
  done
  command -v bash 2>/dev/null
}

# pkexec with an acceptable $SHELL (see mq_sane_shell).
mq_pkexec() {
  local sh
  sh="$(mq_sane_shell)"
  if [[ -n $sh ]]; then
    SHELL="$sh" pkexec "$@"
  else
    pkexec "$@"
  fi
}

# ── One prompt per run ──────────────────────────────────────────────────────
# pkexec prompts on EVERY call (polkit does not cache), so a module with several
# root steps asked several times. Instead, prime `sudo`'s timestamp ONCE through
# a GUI askpass (works with no tty, like the TUI Runner) and let every later
# `sudo`/`mq_sudo` reuse that cache — the standard "one sudo at the start".
# A keep-alive refreshes the timestamp for the whole run. Only when no askpass
# is available do we fall back to the historical pkexec-per-call behaviour.

# GUI password helper for `sudo -A` (no terminal): zenity, else systemd.
mq_sudo_askpass() {
  local f="${XDG_RUNTIME_DIR:-/tmp}/mq-askpass-$UID"
  if [[ ! -x $f ]]; then
    cat > "$f" <<'ASK'
#!/bin/sh
# GUI password prompt for `sudo -A` (generated by mosquitOmarchy).
if command -v zenity >/dev/null 2>&1; then
  exec zenity --password --title="mosquitOmarchy — authentication"
elif command -v systemd-ask-password >/dev/null 2>&1; then
  exec systemd-ask-password --no-tty --timeout=180 "${1:-Password:}"
fi
exit 1
ASK
    chmod +x "$f" 2>/dev/null || { rm -f "$f"; return 1; }
  fi
  [[ -x $f ]] && printf '%s' "$f"
}

# A `sudo` -> pkexec shim on PATH, used ONLY when we could not prime sudo (no
# askpass): child scripts calling `sudo` directly would otherwise hang with no
# tty. Harmless when unused.
mq_enable_sudo_pkexec_shim() {
  [[ -n ${_MQ_SHIM_DIR:-} ]] && return 0
  mq_polkit_agent_usable 2>/dev/null || return 0
  local real
  real="$(command -v sudo 2>/dev/null)" || return 0
  [[ -n $real ]] || return 0
  _MQ_SHIM_DIR="$(mktemp -d)"
  cat > "$_MQ_SHIM_DIR/sudo" <<SH
#!/usr/bin/env bash
# sudo -> pkexec shim (generated by mosquitOmarchy); real sudo: $real
for a in "\$@"; do [[ \$a == -n ]] && exec "$real" "\$@"; done
args=()
while ((\$#)); do
  case "\$1" in
    --) shift; break ;;
    -u) shift; args+=(--user="\$1"); shift ;;
    -v) exec pkexec true ;;
    -E|--preserve-env|--preserve-env=*|-S|-k|--reset-timestamp|-H|--set-home) shift ;;
    -*) shift ;;
    *) break ;;
  esac
done
exec pkexec "\${args[@]}" "\$@"
SH
  chmod +x "$_MQ_SHIM_DIR/sudo"
  export PATH="$_MQ_SHIM_DIR:$PATH"
}

# ── Persistent root helper: ONE pkexec prompt for the whole run ─────────────
# pkexec is the nice, native Omarchy polkit prompt but does not cache, so a
# module with several root steps asked several times. Instead we start a root
# helper ONCE via pkexec; every later root command of the run is executed
# through it (see scripts/lib/mq-root-helper.sh). Same commands, one prompt.
MQ_ROOT_DIR="${MQ_ROOT_DIR:-${XDG_RUNTIME_DIR:-/tmp}/mq-root}"
_MQ_ROOT_HELPER="${MQ_ROOT_HELPER:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/mq-root-helper.sh}"

mq_root_helper_alive() {
  [[ -p "$MQ_ROOT_DIR/req" && -p "$MQ_ROOT_DIR/resp" && -f "$MQ_ROOT_DIR/ready" ]] || return 1
  local owner; owner="$(cat "$MQ_ROOT_DIR/owner" 2>/dev/null || true)"
  [[ $owner =~ ^[0-9]+$ ]] || return 1
  kill -0 "$owner" 2>/dev/null
}

mq_root_helper_start() {
  mq_root_helper_alive && return 0
  [[ -f $_MQ_ROOT_HELPER ]] || return 1
  rm -rf "$MQ_ROOT_DIR" 2>/dev/null || true
  mkdir -p "$MQ_ROOT_DIR" || return 1
  chmod 700 "$MQ_ROOT_DIR"
  mkfifo "$MQ_ROOT_DIR/req" "$MQ_ROOT_DIR/resp" || return 1
  chmod 600 "$MQ_ROOT_DIR/req" "$MQ_ROOT_DIR/resp"
  printf '%s\n' "$$" > "$MQ_ROOT_DIR/owner"
  if [[ -n ${MQ_ROOT_HELPER_NO_ELEVATE:-} ]]; then
    bash "$_MQ_ROOT_HELPER" "$MQ_ROOT_DIR" >/dev/null 2>&1 &         # tests only
  else
    pkexec bash "$_MQ_ROOT_HELPER" "$MQ_ROOT_DIR" >/dev/null 2>&1 &  # one prompt
  fi
  local i
  for ((i = 0; i < 100; i++)); do
    [[ -f "$MQ_ROOT_DIR/ready" ]] && return 0
    sleep 0.1
  done
  rm -rf "$MQ_ROOT_DIR" 2>/dev/null || true   # pkexec cancelled / failed
  return 1
}

mq_root_helper_run() {
  local dir="$MQ_ROOT_DIR" line rc
  { printf '%s\0' "$@"; printf '\0'; } > "$dir/req" 2>/dev/null || return 1
  while IFS= read -r line < "$dir/resp"; do
    if [[ $line == "#__MQ_RC__# "* ]]; then
      rc="${line#\#__MQ_RC__\# }"
      return "${rc:-1}"
    fi
    printf '%s\n' "$line"
  done
  return 1
}

# Prime elevation once. Prefers the persistent root helper (native pkexec
# prompt); falls back to priming sudo's cache via a GUI askpass, then to the
# per-call pkexec shim. Idempotent.
mq_sudo_prime() {
  [[ -n ${MQ_SUDO_PRIMED:-} ]] && return 0
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
    MQ_SUDO_PRIMED=1; MQ_PRIME_KIND=root; export MQ_SUDO_PRIMED MQ_PRIME_KIND; return 0
  fi
  if sudo -n -v 2>/dev/null; then
    MQ_SUDO_PRIMED=1; MQ_PRIME_KIND=sudo; export MQ_SUDO_PRIMED MQ_PRIME_KIND; return 0
  fi
  # Preferred: one pkexec prompt, reused for the whole run.
  if mq_polkit_agent_usable && mq_root_helper_start; then
    MQ_SUDO_PRIMED=1; MQ_PRIME_KIND=helper; export MQ_SUDO_PRIMED MQ_PRIME_KIND; return 0
  fi
  # Fallback: prime sudo through the GUI askpass.
  local ap
  ap="$(mq_sudo_askpass)" || { mq_enable_sudo_pkexec_shim; return 1; }
  if SUDO_ASKPASS="$ap" sudo -A -v; then
    export SUDO_ASKPASS="$ap"
    MQ_SUDO_PRIMED=1; MQ_PRIME_KIND=sudo; export MQ_SUDO_PRIMED MQ_PRIME_KIND
    ( _mq_pp=$PPID; while kill -0 "$_mq_pp" 2>/dev/null; do sudo -n -v 2>/dev/null; sleep 50; done ) </dev/null >/dev/null 2>&1 &
    disown 2>/dev/null || true
    return 0
  fi
  mq_enable_sudo_pkexec_shim
  return 1
}

# mq_sudo_noninteractive CMD [ARGS...] — never prompt: root runs directly,
# everyone else gets `sudo -n` (for NOPASSWD / already-cached credentials).
mq_sudo_noninteractive() {
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
    "$@"
  else
    sudo -n "$@"
  fi
}

# mq_sudo CMD [ARGS...] — run a command as root (see the header above).
# Also accepts the two sudo-compatible forms used in this repo:
#   mq_sudo -v      check that elevation is possible (no command run)
#   mq_sudo -n CMD  non-interactive (same as mq_sudo_noninteractive CMD)
mq_sudo() {
  case ${1:-} in
    -v)
      [[ ${EUID:-$(id -u)} -eq 0 ]] && return 0
      sudo -n -v 2>/dev/null && return 0
      mq_sudo_prime && return 0
      mq_polkit_agent_usable && return 0
      return 1
      ;;
    -n)
      shift
      mq_sudo_noninteractive "$@"
      return $?
      ;;
  esac
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
    "$@"; return $?
  fi
  if [[ ${MQ_PRIME_KIND:-} == helper ]] && mq_root_helper_alive; then
    mq_root_helper_run "$@"; return $?
  fi
  if sudo -n -v 2>/dev/null; then
    sudo "$@"; return $?
  fi
  if [[ ${MQ_PRIME_KIND:-} == sudo ]]; then
    sudo "$@"; return $?
  fi
  if mq_sudo_prime; then
    if [[ ${MQ_PRIME_KIND:-} == helper ]] && mq_root_helper_alive; then
      mq_root_helper_run "$@"; return $?
    fi
    sudo "$@"; return $?
  fi
  if mq_polkit_agent_usable; then
    mq_pkexec "$@"; return $?
  fi
  sudo "$@"
}
