#!/usr/bin/env bash
# Shared resolution + application of the wine runtime a DAW must launch under.
#
# Why this file exists: a wine VST3 editor that builds a DirectComposition
# surface dies during editor creation on stock wine-staging
# (STATUS_STACK_BUFFER_OVERRUN / c0000409 inside dcomp). Serum 2 does exactly
# that. Only the ableton-linux fork (~/.local/opt/wine-d2d1-nspa-*) has working
# DComp, so a DAW launched with the system wine cannot open that editor even
# though the plugin is installed and yabridged correctly.
#
# This was hand-fixed once in ~/.local/bin/reaper, a wrapper nothing launched,
# while the desktop entry pointed at a different wrapper that used the system
# wine -- so the fix looked applied and was not. Both launchers are generated
# from here now, and the audio plugin manager re-applies them after installing
# a plugin that is known to need this runtime.
#
# Source it, do not execute it.

# The canonical runtime's bin directory, or empty when it is not installed.
# The name is matched exactly: siblings sitting next to it are dated
# *-rollback-* safety copies and aborted *.transaction-installer.* directories,
# and a plain glob would let the aborted one sort last and win.
mosquitomarchy_nspa_wine_dir() {
  local c d
  for c in "$HOME"/.local/opt/wine-d2d1-nspa-*/bin; do
    [[ -x $c/wine ]] || continue
    d="$(basename "$(dirname "$c")")"
    [[ $d =~ ^wine-d2d1-nspa-[0-9]+(\.[0-9]+)*$ ]] || continue
    mosquitomarchy_nspa_wine_dir="$c"
  done
  printf '%s' "${mosquitomarchy_nspa_wine_dir:-}"
}

# Which runtime does a DAW wrapper currently launch under?
#   prints "nspa" | "system" | "absent"
mosquitomarchy_daw_wrapper_runtime() {
  local w="$1"
  [[ -f $w ]] || { printf 'absent'; return; }
  if grep -q 'wine-d2d1-nspa' "$w" 2>/dev/null; then printf 'nspa'; else printf 'system'; fi
}

# Is a wrapper already launching under exactly this runtime dir?
mosquitomarchy_daw_wrapper_points_at() {
  local w="$1" dir="$2"
  [[ "$(mosquitomarchy_daw_wrapper_runtime "$w")" == nspa ]] || return 1
  grep -qF -- "$dir" "$w" 2>/dev/null
}

# Rewrite a DAW wrapper so it launches under the patched runtime.
#   $1 = wrapper path
#   $2 = the real binary the wrapper execs
#   $3 = "noscale" to keep the caller's GDK_* variables (REAPER wants them
#        dropped, Bitwig has always run with them)
# Returns 1 (and changes nothing) when the runtime is not installed: silently
# writing a wrapper that falls back to the system wine is what made the original
# bug invisible.
mosquitomarchy_write_daw_wrapper() {
  local w="$1" bin="$2" mode="${3:-}" dir exec_line
  dir="$(mosquitomarchy_nspa_wine_dir)"
  if [[ -z $dir ]]; then
    return 1
  fi
  if [[ $mode == noscale ]]; then
    exec_line="exec $bin \"\$@\""
  else
    exec_line="exec /usr/bin/env -u GDK_SCALE -u GDK_DPI_SCALE -u QT_SCALE_FACTOR $bin \"\$@\""
  fi
  cat > "$w" <<EOF
#!/usr/bin/env bash
# Generated by mosquitomarchy (scripts/lib/wine-runtime-daw.bash).
# Patched wine runtime first in PATH: a DComp VST3 editor (Serum 2) cannot be
# created under stock wine-staging. Regenerate by re-running the setup, do not
# hand-edit -- an edit that drops this block turns the crash back on.
AWINE_DIR="$dir"
if [ -x "\$AWINE_DIR/wine" ]; then
  export PATH="\$AWINE_DIR:\$PATH"
fi
$exec_line
EOF
  chmod +x "$w"
}

# Apply the runtime to every DAW wrapper we own. Idempotent: it rewrites only
# when the current state would leave a DAW on the wrong wine.
#   $1 = "quiet" to stay silent when there is nothing to do
mosquitomarchy_apply_daw_wine_runtime() {
  local quiet="${1:-}" dir rc=0 changed=0
  dir="$(mosquitomarchy_nspa_wine_dir)"
  if [[ -z $dir ]]; then
    [[ $quiet == quiet ]] || {
      echo "warning: no wine-d2d1-nspa runtime in ~/.local/opt -- DAWs keep the" >&2
      echo "         system wine, and DComp VST3 editors (Serum 2) will crash" >&2
      echo "         on open. Run the Ableton setup to install it." >&2
    }
    return 1
  fi

  # REAPER: the desktop entry cockos-reaper.desktop launches this wrapper.
  if [[ -x /usr/lib/REAPER/reaper || -x /opt/REAPER/reaper ]]; then
    local rbin="" w="$HOME/.local/bin/reaper-launch"
    [[ -x /usr/lib/REAPER/reaper ]] && rbin=/usr/lib/REAPER/reaper || rbin=/opt/REAPER/reaper
    if ! mosquitomarchy_daw_wrapper_points_at "$w" "$dir"; then
      mkdir -p "$HOME/.local/bin"
      if mosquitomarchy_write_daw_wrapper "$w" "$rbin"; then
        changed=1
      else
        rc=1
      fi
    fi
  fi

  # Bitwig: same editor, same crash, and its wrapper was hand-written with the
  # runtime path hardcoded, so it silently broke on the next version bump.
  if [[ -x /usr/bin/bitwig-studio ]]; then
    local w="$HOME/.local/bin/bitwig-studio"
    if ! mosquitomarchy_daw_wrapper_points_at "$w" "$dir"; then
      if mosquitomarchy_write_daw_wrapper "$w" /usr/bin/bitwig-studio noscale; then
        changed=1
      else
        rc=1
      fi
    fi
  fi

  if (( changed )) && [[ $quiet != quiet ]]; then
    echo "DAW wine runtime set to the patched build: $dir"
  fi
  return $rc
}
