#!/usr/bin/env bash
# setup-crunchycleaner-menu.sh — Crunchy Cleaner integration: pkexec launcher +
# menu entry + icon.
# =============================================================================
# Crunchy Cleaner (AUR package "crunchycleaner-bin") cleans system caches and
# junk, so it needs root for most of its work. Its package ships a bare
# `Exec=crunchycleaner` desktop entry (and no prompt), so the app fails or does
# nothing on the system paths. This companion installs a wrapper that runs it
# through the native polkit prompt (pkexec):
#   • pkexec `crunchycleaner`               → the normal, authorized launch;
#   • if the pkexec dialog is DISMISSED (Esc / cancel, exit 126) the app is
#     started WITHOUT root, so the user is never left stuck.
#
# Called by setup-tuis.sh right after the AUR install (a script named
# setup-<base>-menu.sh is auto-run for its catalog entry); standalone too.
#
# Usage:
#   ./setup-crunchycleaner-menu.sh            # applies (idempotent)
#   ./setup-crunchycleaner-menu.sh --remove   # removes the launcher + entry
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

info() { echo -e "\033[1;34m==>\033[0m $*"; }
ok()   { echo -e "\033[1;32m ✓\033[0m $*"; }
warn() { echo -e "\033[1;33m !\033[0m $*"; }

BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications"
ICONS_DIR="$HOME/.local/share/icons/hicolor/256x256/apps"
WRAPPER="$BIN_DIR/crunchycleaner-root"
DESKTOP="$APPS_DIR/crunchycleaner.desktop"
ICON_SRC="$SCRIPT_DIR/crunchycleaner-logo.png"

REMOVE=0
for a in "$@"; do case "$a" in
  --remove) REMOVE=1 ;;
  -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
  *) echo "Unknown option: $a (supported: --remove)" >&2; exit 1 ;;
esac; done

if ((REMOVE)); then
  rm -f "$WRAPPER" "$DESKTOP"
  ok "crunchycleaner launcher/entry removed"
  exit 0
fi

# ── Launcher wrapper: pkexec, with a no-root fallback on dismissal ───────────
info "Installing the pkexec launcher $WRAPPER"
mkdir -p "$BIN_DIR"
cat > "$WRAPPER" <<'WRAP'
#!/usr/bin/env bash
# crunchycleaner-root — run Crunchy Cleaner as root via pkexec. If the polkit
# authentication dialog is dismissed (Esc / cancel → pkexec exit 126), start it
# WITHOUT root instead of doing nothing. Generated by setup-crunchycleaner-menu.sh.
set -u
BIN="$(command -v crunchycleaner || echo /usr/bin/crunchycleaner)"

if command -v pkexec >/dev/null 2>&1; then
  # pkexec refuses a $SHELL that is not listed in /etc/shells.
  sh="${SHELL:-}"
  grep -qxF "$sh" /etc/shells 2>/dev/null || sh=/bin/bash
  SHELL="$sh" pkexec "$BIN" "$@"
  rc=$?
  # 125/126/127 = pkexec could not run it (dismissed, not authorized, no agent):
  # fall back to a normal, non-root launch so the tool still opens.
  if (( rc == 125 || rc == 126 || rc == 127 )); then
    echo "pkexec cancelled — launching crunchycleaner without root…" >&2
    exec "$BIN" "$@"
  fi
  exit "$rc"
fi

exec "$BIN" "$@"
WRAP
chmod +x "$WRAPPER"
ok "launcher: $WRAPPER"

# ── Icon ─────────────────────────────────────────────────────────────────────
if [[ -f "$ICON_SRC" ]]; then
  mkdir -p "$ICONS_DIR"
  cp -f "$ICON_SRC" "$ICONS_DIR/crunchycleaner.png"
  command -v gtk-update-icon-cache >/dev/null 2>&1 \
    && gtk-update-icon-cache -f -t "$HOME/.local/share/icons/hicolor" >/dev/null 2>&1 || true
  ok "icon: $ICONS_DIR/crunchycleaner.png"
fi

# ── Desktop entry (Exec → the pkexec wrapper, terminal TUI) ──────────────────
info "Installing the menu entry $DESKTOP"
mkdir -p "$APPS_DIR"
cat > "$DESKTOP" <<DESK
[Desktop Entry]
Type=Application
Name=crunchycleaner
GenericName=Cache & junk cleaner
Comment=Cleans system caches & junk (pkexec; runs without root if you cancel)
Exec=$WRAPPER
Terminal=true
Icon=crunchycleaner
Categories=Utility;System;
DESK
command -v update-desktop-database >/dev/null 2>&1 \
  && update-desktop-database "$APPS_DIR" 2>/dev/null || true
ok "menu entry: $DESKTOP (pkexec, non-root fallback on Esc)"
